#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use SoCli\CommandManager;
use Symfony\Component\Console\Application;

$application = new Application();

$command_manager = new CommandManager();
$commands = $command_manager->getCommands();
$application->addCommands($commands);

$application->run();