#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use SoCli\CommandManager;
use SoCli\Command\PullCommands;
use Symfony\Component\Console\Application;


$application = new Application();
$application->addCommands([
  new PullCommands(),
]);

$command_manager = new CommandManager();
$commands = $command_manager->getCommands();
$application->addCommands($commands);

$application->run();